### ISSUE TITLE
get rid of jwlib/jwlink

### ISSUE THREAD

**Issue by stsp** [stsp/fdpp#11]
Study how Bart did that for FreeDOS and do the same here.

**Comment by stsp** [comment]
I fully ported Bart's patch and converted most
of the fdpp-specific asm too. There remained only
3 "SEG" operators in plt.S, and getting rid of them
looks very very difficult...

**Comment by stsp** [comment]
In this patch: https://github.com/stsp/fdpp/commit/a545f3a94fb3f6bdef88d028121b9fa07717e76f
I tried to switch to elf build, but it doesn't work.
I am getting the empty relocation table:
```
                0x0000001c                __msdos_mz_rel_start = .
 *(.msdos_mz_reloc .msdos_mz_reloc.*)
                0x0000001c                __msdos_mz_rel_end = .
                0x00000020                . = ALIGN (0x10)
```

@tkchia could you please give me an advice,
how is the relocation table supposed to be generated?
elf build in fdpp is much more difficult than in freedos,
but I did most of the work already. Relocs seems to be
the last obstacle.

**Comment by tkchia** [comment]
Hello @stsp ,

> @tkchia could you please give me an advice, how is the relocation table supposed to be generated?

I think a good way might be to rewrite the parts that require relocation tables, i.e. `plt.asm`, to use the patched GNU assembler in the toolchain, i.e. `ia16-elf-as`.   I added some "ELF" relocation types to `binutils-ia16` to specifically support `MZ` relocations, so that under `ia16-elf-as` you can write, say,
```
.hword foo
.reloc ., R_386_SEGMENT16, foo
.hword 0
```
to emit a far pointer to a `foo` symbol.  (And indeed this is similar to what `ia16-elf-gcc` does to emit pointers to far variables.)

If you wish to stick with `nasm`, one possible way would be to manually populate the `.msdos_mz_reloc` segment with the actual `MZ` relocation entries --- you can do this --- though naturally this will not be very neat.  Alas, `nasm` most probably does not know about the special relocation types.

I hope this helps for now.  Thank you!

**Comment by stsp** [comment]
So did freedos moved away from nasm, too?
Oh, I wasn't planning that.
This explains why I didn't get relocation tables
even with ia16-elf-ld. Does ia16-elf-as use the
same syntax, so the move is not very painful?
I'll think if I should follow that, or stick to nasm...

**Comment by andrewbird** [comment]
No sure how functional it is but there's an alpha 'djlink' which supports OMF http://www.delorie.com/djgpp/16bit/djlink/

**Comment by tkchia** [comment]
Hello @stsp ,

> So did freedos moved away from nasm, too?

I think the assembly language portions of the FreeDOS kernel are still very much written in `nasm`.  But if I am not wrong the portions that make use of `MZ` relocations are written in C (which internally go through `ia16-elf-as`).

Thank you!

**Comment by stsp** [comment]
I don't understand how can this be so.
When I look into what I have now with fdpp,
I see it crashes right in the `jmp     IGROUP:kernel_start`,
`kernel.asm:108`.
So I think relocations are involved in every long jump here,
and that very much includes all the nasm sources too.

@andrewbird thanks for the pointer! Something like
a few months ago I would take that. But now the motto
is "fdpp: do it differently!", so I really am thinking about
avoiding both omf and ia16-gcc-ld (unless I can get the
relocations to work somehow).

**Comment by stsp** [comment]
OK, I've found out why the stripped down kernel.ld
from freedos didn't work for me with normal GNU ld:
that's because it was missing the alignment for
some sections. After fixing this, I can now link
fdpp w/o ia16-gcc-ld, and I don't need a relocation
table at all.

**Comment by stsp** [comment]
Sure, its still there. ld can also generate map.
Btw, I decided to finally remove freedos remnants
from this repo. Now we have a small and lean repo.

**Comment by stsp** [comment]
Would be good to get things tested.
This is a very important milestone, so I am
going to tag a new beta soon.

**Comment by stsp** [comment]
@tkchia so I think you were right
when describing the new relocation
scheme of freedos. Since my problem
appears to be in section alignments,
not in relocations, nothing contradicts
what you said. Its just that in case of
omf, the nasm-compiled files used the
exe relocations for sure. So I expected
the same from an elf scheme too, but
it seems nasm relocations are now
resolved at link time. In which case I
wonder why not to do the same with C
relocations, instead of using exeflat?

**Comment by stsp** [comment]
@tkchia please join this thread:
https://bugzilla.nasm.us/show_bug.cgi?id=3392533
I think nasm authors would be happy to know
about the new relocation types.
I wonder if this will in the future be available in
a regular ld, or will always be specific to ia16-elf-ld?
(you are welcome to answer that in an aforementioned
thread :)

**Comment by stsp** [comment]
> Alas, nasm most probably does not know about the special relocation types.

So yes, before nasm is teached about them,
this work can't be considered completed.
fdpp builds even now, but I had to write the
relocation machinery that looks up the segments
with objdump+grep. This is very slow and ugly.
I'll be happy to drop that and use whatever nasm
is to provide in the future.

**Comment by tkchia** [comment]
Hello @stsp ,

> @tkchia please join this thread: https://bugzilla.nasm.us/show_bug.cgi?id=3392533

Thank you!  I have set up an account there, and I hope to join the discussion soon (when I have a bit more time).  Anyway, I am still not very satisfied with the way I implemented the new "ELF" relocations in `binutils-ia16` --- it is very hacky and very `MZ`-centric --- so it will probably undergo _some_ changes at the least before I try to get it upstream.

(Well, in my defence, this was because I found the existing ELF code to be extremely spaghetti-like, and I wanted to find a way to add the `MZ` support without wrecking too many things...)

> So I expected the same from an elf scheme too, but it seems nasm relocations are now resolved at link time. In which case I wonder why not to do the same with C relocations, instead of using exeflat?

I think it is roughly like this:  In the general case, when linking a normal "userland" `.exe` program, we cannot tell beforehand which paragraph in conventional memory the `.exe` will be loaded at, so the relocation entries are needed for static far pointers.  The compiled C modules are meant to work in this general case.

In the case of the kernel --- as I just recalled --- we _know_ where exactly in conventional memory we want to load it.  So basically the `nasm`'d modules use this fact to "cheat" a bit: e.g. we know that `.ptext` will be at `0x60:0` and nowhere else, so we can arrange to compute an absolute value `PGROUP` in `kernel.ld` which is equal to `0x60` to refer to `.ptext`.

Thank you!

**Comment by stsp** [comment]
> --- it is very hacky and very MZ-centric --- so it will probably undergo some changes
> at the least before I try to get it upstream.

Does this mean you will only change the implementation,
or the semantic as well? If you are not going to change the
semantic, I suppose this is a good time to announce this to
nasm devs.
So could you please clarify, will you get it upstream as
ia16-elf-ld, or into a casual ld?

> In the case of the kernel --- as I just recalled --- we know where exactly in conventional
> memory we want to load 

Yes, this is clear of course. :)
My question was, since in freedos you compile the _kernel_
(even if from C code), why not to resolve _all_ the relocation
at link time? You seem to resolve only nasm relocations and
generate .exe for C relocations. What if you flatten all relocations
at once and bypass the .exe stage completely?
I understand you may still need .exe and its relocations for
other projects, but my question is about freedos.

**Comment by tkchia** [comment]
Hello @stsp ,

> But I wonder why you never answer whether your changes are going to land to generic ld or to special ia16-elf-ld.

On that, I think I will defer to the upstream maintainer of `binutils-ia16`, i.e. Mr. Jenner.  So I think the changes will probably be limited to `ia16-elf-ld` for the near future, unless something interesting happens.

Thank you!

**Comment by stsp** [comment]
> changes will probably be limited to ia16-elf-ld for the near future

Ah, that will trouble its use for nasm I suppose...
